name: Invoke CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    name: Build & Test (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Build Server Binary
        run: go build -v -o invoke-server.exe .

      - name: Build App Launcher Binary
        run: go build -v -o invoke-app.exe .\cmd\invoke-app\

  test-and-build-linux:
    name: Build & Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'
      - name: Run Unit Tests
        run: go test -v ./...
      - name: Build Server Binary
        run: go build -v -o invoke-server-linux .
      - name: Build App Launcher Binary
        run: go build -v -o invoke-app-linux ./cmd/invoke-app/

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=jdmldm1
            -Dsonar.projectKey=jdmldm1_Invoke
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
